name: APK Build and Com

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.24.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flet

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build APK with Flet Pack
      run: |
        flutter config --no-analytics # Disable Flutter analytics
        flet pack android --release

    - name: Optimize APKs
      run: |
        mkdir -p optimized-apks
        zipalign -v -p 4 build/app/outputs/flutter-apk/app-release.apk optimized-apks/app-aligned-release.apk
        zipalign -v -p 4 build/app/outputs/flutter-apk/app-release.apk optimized-apks/app-arm64-aligned-release.apk

        # Optional: Verify alignment
        zipalign -c 4 optimized-apks/app-aligned-release.apk

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: optimized-apk-artifacts
        path: optimized-apks/
        if-no-files-found: error
