name: Build Flet APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-flet-apk:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Step 3: Install Flet CLI and dependencies
    - name: Install Flet CLI and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet
        pip install -r requirements.txt
        flet pack init

    # Step 4: Install Flutter and Android SDK
    - name: Install Flutter and Android SDK
      run: |
        # Install dependencies
        sudo apt update
        sudo apt install -y curl unzip openjdk-11-jdk wget
        # Download and install Flutter
        curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.13.5-stable.tar.xz
        tar xf flutter_linux_3.13.5-stable.tar.xz
        export PATH=$PWD/flutter/bin:$PATH
        flutter --version
        # Install Android SDK and Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmd-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip cmd-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    # Step 5: Build APK
    - name: Build Flet APK
      run: |
        export PATH=$PWD/flutter/bin:$PATH
        flutter pub get
        flet pack android

    # Step 6: Upload APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app.apk
        path: build/app/outputs/flutter-apk/app-release.apk
